dna/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload_dna.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

upload_dna/urls.py
from django.urls import path
from . import views
from upload_dna.models import Data
from django.views.generic import ListView, DetailView

app_name = 'upload'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('', views.home, name='home'),
    path('upload/add/', views.DataCreate.as_view(), name='data_add'),
    path('upload/detail/', views.detail, name='detail'),
    path('register/', views.UserFormView.as_view(), name='register'),
]

upload_dna/models.py
from __future__ import unicode_literals
from django.db import models
from django import forms
from django.urls import reverse

class Data(models.Model):
    user = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    file = models.FileField()

    def get_absolute_url(self):
        return reverse('upload:detail')

    def __str__(self):
        return self.user

upload_dna/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

upload_dna/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.views.generic import View
from .models import Data
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login
import numpy as np
import pandas as pd

class UserFormView(View):
    form_class = UserForm
    template_name = 'upload_dna/registration_form.html'

    #display form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #add user
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('upload:home')

        return render(request, self.template_name, {'form': form})

class DataCreate(CreateView):
    model = Data
    fields = ['user', 'file']

def upload(request):
    return render(request, 'upload_dna/upload.html')

def home(request):
    return render(request, 'upload_dna/home.html')

def detail(request):
    all_data = Data.objects.all()
    posts = Data.objects.all().order_by('-created')[:5]
    latest_entry = posts[0]

    df = pd.read_csv('./media/AncestryDNA.txt', comment="#", sep='\s+',)
    df = df[["rsid","chromosome","position","allele1","allele2",]]
    data_table = df.to_html(index=False)

    args = {'all_data': all_data, 'posts': posts, 'latest_entry': latest_entry, 'df': df, 'data_table': data_table }

    return render(request, 'upload_dna/detail.html', args)

upload_dna/templates/upload_dna/data_form.html
{% extends "upload_dna/header.html" %}
{% load staticfiles %}

{% block content %}

<div class = "container">
  <div class="row">
    <form class='form-horizontal' action= "" method ="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'upload_dna/form-template.html' %}
      <div class="form-group">
        <div>
          <button type="submit">Submit</button>
          <p>data form</p>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

upload_dna/templates/upload_dna/detail.html
{% extends "upload_dna/header.html" %}

{% block content %}
        <h5>{{ latest_entry }} loaded successfully</h5>

        <div>
          {{ data_table|safe }}
        </div>
        <!-- <ul>
        {% for data in all_data %}
            <h5>{{ data }}</h5>
        {% endfor %}
        </ul> -->

{% endblock %}

upload_dna/templates/upload_dna/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col=sm-10">
      <span class="text-danger small">{{ field.error }}</span>
    </div>
    <label class="control-label">{{ field.label_tag }}</label>
    <div>
      {{ field }}
    </div>
  </div>
{% endfor %}

upload_dna/templates/upload_dna/header.html
<!doctype html>
<html lang="en">
{% load static %}
{% load staticfiles %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link  rel="stylesheet" href="{% static 'upload_dna/css/header.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <div class="navbar navbar-dark bg-dark id="navbar" ">
      <a class="navbar-brand" href='/'>DNA</a>
  </div>

  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

upload_dna/templates/upload_dna/home.html
{% extends "upload_dna/materialize.html" %}
{% load staticfiles %}

{% block content %}
<div class = "container">
  <div class="row">
     <div class="col m4">
       <div class="card blue-grey darken-1">
         <div class="card-image">
            <img src="../static/upload_dna/img/hadron.jpg">
            <span class="card-title"></span>
          </div>
         <div class="card-content white-text">
           <br></br>
           <span class="card-title">Upload</span>
           <p>Upload DNA File</p>
         </div>
         <div class="card-action">
           <a href="upload">Upload</a>
         </div>
       </div>
       </div>
       <!-- card2 -->
       <div class="col m4">
       <div class="card blue-grey darken-1">
         <div class="card-image">
            <img src="../static/upload_dna/img/hadron.jpg">
            <span class="card-title"></span>
          </div>
         <div class="card-content white-text">
           <br></br>
           <span class="card-title">Review</span>
           <p>Analyze Your Results</p>
         </div>
         <div class="card-action">
           <a href="upload">Upload</a>
         </div>
       </div>
       </div>
       <!-- card3 -->
       <div class="col m4">
       <div class="card blue-grey darken-1">
         <div class="card-image">
            <img src="../static/upload_dna/img/hadron.jpg">
            <span class="card-title"></span>
          </div>
         <div class="card-content white-text">
           <br></br>
           <span class="card-title">Discuss</span>
           <p>Join The Forum</p>
         </div>
         <div class="card-action">
           <a href="upload">Upload</a>
         </div>
       </div>
     </div>
   </div>
</div>
{% endblock %}

upload_dna/templates/upload_dna/materialize.html
<!doctype html>
<html lang="en">
{% load static %}
{% load staticfiles %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'upload_dna/css/header.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

    <nav>
      <div class="nav-wrapper black">
        <a href="" class="brand-logo">DNA</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="badges.html"><i class="material-icons right">view_module</i></a></li>
        </ul>
      </div>
    </nav>

  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</body>

</html>

upload_dna/templates/upload_dna/registration_form.html
{% extends "upload_dna/header.html" %}
{% load staticfiles %}

{% block content %}

<div class = "container">
  <div class="row">
    <h1>REGISTER</h1>
    <form class='form-horizontal' action= "" method ="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'upload_dna/form-template.html' %}
      <div class="form-group">
        <div>
          <button type="submit">Submit</button>
          <p>data form</p>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

upload_dna/templates/upload_dna/upload.html
{% extends "upload_dna/header.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
<h1>You agree to all the things</h1>
<form action="{% url 'upload:data_add' %}">
    <input type="submit" value="Agree" />
</form>
</div>
{% endblock %}